from ctypes import *

class spcmodinfo(Structure):
	_fields_=[('module_type', c_short),
			  ('bus_no', c_short),
			  ('slot_no', c_short),
			  ('in_use', c_short),
			  ('init', c_short),
			  ('base_adr', c_ushort)]
			  
class spcrates(Structure):
	_fields_=[('sync_rate', c_float),
			  ('cfd_rate', c_float),
			  ('tac_rate', c_float),
			  ('adc_rate', c_float)]

spcinfo_comments=['base I/O address on PCI bus', 
				'set to initialisation result code', 
				'= CFD_TH1 threshold of CFD1', 
				'= CFD_TH2 threshold of CFD2', 
				'= CFD_TH3 threshold of CFD3', 
				'= CFD_TH4 threshold of CFD4', 
				'= CFD_ZC1 Zero Cross level of CFD1', 
				'= CFD_ZC2 Zero Cross level of CFD2', 
				'= CFD_ZC3 Zero Cross level of CFD3', 
				'DPC range in TCSPC and Multiscaler mode', 
				'1,2,4', 
				'not used for DPC230', 
				'TDC offset in TCSPC and Multiscaler mode', 
				'not used for DPC230', 
				'= CFD_ZC4 Zero Cross level of CFD4', 
				'no of points of decay curve', 
				'not used for DPC230', 
				'0.0001 .. 100000s , default 2.0s', 
				'not used for DPC230', 
				'not used for DPC230', 
				'1 (stop) or 0 (no stop)', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'DPC/TDC active', 
				'not used for DPC230', 
				'not used for DPC230', 
				'DPC230  bits 0-7 - control bits', 
				'macro time clock in ps', 
				'module no on PCI bus ( 0-7)', 
				'module\'s operation mode', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230',
				'not used for DPC230', 
				'source of pixel clock in Image modes', 
				'not used for DPC230', 
				'external trigger condition', 
				'not used for DPC230', 
				'not used for DPC230', 
				'rate counting time in sec', 
				'not used for DPC230', 
				'not used for DPC230', 
				'EEPROM', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'not used for DPC230', 
				'type of active inputs', 
				'not used for DPC230', 
				'enable(1)/disable(0) input channels', 
				'active slope of input channels', 
				'channel numbers of special inputs']
