# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cross_correlate', [dirname(__file__)])
        except ImportError:
            import _cross_correlate
            return _cross_correlate
        if fp is not None:
            try:
                _mod = imp.load_module('_cross_correlate', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cross_correlate = swig_import_helper()
    del swig_import_helper
else:
    import _cross_correlate
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class array(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, array, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, array, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _cross_correlate.new_array(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cross_correlate.delete_array
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _cross_correlate.array___getitem__(self, *args)
    def __setitem__(self, *args): return _cross_correlate.array___setitem__(self, *args)
    def cast(self): return _cross_correlate.array_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _cross_correlate.array_frompointer
    if _newclass:frompointer = staticmethod(_cross_correlate.array_frompointer)
array_swigregister = _cross_correlate.array_swigregister
array_swigregister(array)

def array_frompointer(*args):
  return _cross_correlate.array_frompointer(*args)
array_frompointer = _cross_correlate.array_frompointer


def open_counted_file(*args):
  return _cross_correlate.open_counted_file(*args)
open_counted_file = _cross_correlate.open_counted_file

def close_counted_file():
  return _cross_correlate.close_counted_file()
close_counted_file = _cross_correlate.close_counted_file

def read_metadata():
  return _cross_correlate.read_metadata()
read_metadata = _cross_correlate.read_metadata

def read_chunk():
  return _cross_correlate.read_chunk()
read_chunk = _cross_correlate.read_chunk
# This file is compatible with both classic and new-style classes.


